/**
 * Edit-noise filtering — what counts as a real, authored edit.
 * Run: node --test tests/editNoiseFilter.test.mjs
 *
 * edit_events feeds hot-files, churn coloring, the treemap, and the health
 * score, so a path that leaks through the filter is ranked as if a human wrote
 * it. Each case below is a class of leak observed in production data.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const helpers = path.resolve(import.meta.dirname, '../.claude/helpers');
// The watcher (write time) and db.cjs (read time) must both resolve to the
// single definition in path-filter.cjs — asserting through all three surfaces
// is what proves they cannot drift apart.
const { shouldIgnore, isGitIgnoredDir } = await import(pathToFileURL(path.join(helpers, 'watcher.mjs')).href);
const { isNoiseEditPath, mergePathCasing, canonicalizePath } = require('../.claude/helpers/path-filter.cjs');
const db = require('../.claude/helpers/db.cjs');

// ── watcher-side filtering (blocks junk at write time) ─────────────────────

test('vaultflow never records its own .metrics telemetry as a user edit', () => {
  // 5,707 such rows existed; agent-context.json alone was the #2 "hot file".
  assert.equal(shouldIgnore('C:\\GIT\\vaultflow\\.metrics\\agent-context.json'), true);
  assert.equal(shouldIgnore('C:/GIT/vaultflow/.metrics/sessions/current-BUZZ.json'), true);
});

test('vaultflow does not record the context files it generates itself', () => {
  // gen-context.mjs rewrites these on every session start and on the watcher's
  // periodic sweep, so vaultflow's own output became the top "hot files" in
  // projects it had merely visited (AGENTS.md: 378 "edits").
  for (const p of [
    'C:\\GIT\\proj\\AGENTS.md',
    'C:\\GIT\\proj\\.github\\copilot-instructions.md',
    'C:\\GIT\\proj\\.cursor\\rules\\wiki.mdc',
    'C:\\GIT\\proj\\.vscode\\mcp.json',
    'C:\\GIT\\proj\\.mcp.json',
  ]) {
    assert.equal(isNoiseEditPath(p, { useGit: false }), true, `${p} is generated by vaultflow`);
  }
  // ...but a file that merely mentions agents is still real source.
  assert.equal(isNoiseEditPath('C:\\GIT\\proj\\src\\agents.ts', { useGit: false }), false);
  assert.equal(isNoiseEditPath('C:\\GIT\\proj\\docs\\AGENTS.md.bak', { useGit: false }), false);
});

test('binary database files are not edits', () => {
  // The old list ignored .db and .duckdb.wal but not .duckdb, so another
  // project's market.duckdb ranked as the single hottest file on the machine.
  assert.equal(shouldIgnore('C:\\GIT\\StockTool\\data\\market.duckdb'), true);
  assert.equal(shouldIgnore('C:\\GIT\\x\\app.sqlite3'), true);
  assert.equal(shouldIgnore('C:\\GIT\\x\\app.db'), true);
});

test('git scratch directories are ignored, not just .git itself', () => {
  // /\.git[\/\\]/ requires a separator right after ".git", so .git-rewrite slipped past.
  assert.equal(shouldIgnore('C:\\GIT\\BusinessCentral\\.git-rewrite\\heads'), true);
  assert.equal(shouldIgnore('C:\\GIT\\proj\\.git\\HEAD'), true);
});

test('.NET build output and pycache are ignored on Windows paths', () => {
  // The old __pycache__ rule only matched forward slashes, so it never fired on Windows.
  assert.equal(shouldIgnore('C:\\GIT\\proj\\bin\\Debug\\app.dll'), true);
  assert.equal(shouldIgnore('C:\\GIT\\proj\\src\\__pycache__\\mod.pyc'), true);
});

test('authored source is never ignored', () => {
  for (const p of [
    'C:\\Git\\vaultflow\\.claude\\helpers\\db.cjs',
    'C:\\Git\\vaultflow\\scripts\\install.mjs',
    'C:\\Git\\vaultflow\\CLAUDE.md',
  ]) {
    assert.equal(shouldIgnore(p), false, `${p} must count as a real edit`);
  }
});

// ── gitignore awareness (per-project definition of "generated") ────────────

test('a directory the repo gitignores is treated as generated', (t) => {
  // A global pattern list cannot safely block names like `public/` — React
  // projects author into it, static-site generators build into it. The repo's
  // own .gitignore is the authoritative answer, so defer to git.
  const repo = fs.mkdtempSync(path.join(os.tmpdir(), 'vf-gitignore-'));
  try {
    execFileSync('git', ['init', '-q'], { cwd: repo, stdio: 'ignore' });
  } catch { return t.skip('git not available'); }

  fs.writeFileSync(path.join(repo, '.gitignore'), 'public\n');
  fs.mkdirSync(path.join(repo, 'public', 'nested'), { recursive: true });
  fs.mkdirSync(path.join(repo, 'src'), { recursive: true });

  assert.equal(isGitIgnoredDir(path.join(repo, 'public')), true, 'ignored dir');
  assert.equal(isGitIgnoredDir(path.join(repo, 'public', 'nested')), true, 'nested under ignored dir');
  assert.equal(isGitIgnoredDir(path.join(repo, 'src')), false, 'tracked dir must stay visible');

  assert.equal(shouldIgnore(path.join(repo, 'public', 'sitemap.xml')), true);
  assert.equal(shouldIgnore(path.join(repo, 'src', 'index.ts')), false);
});

// ── read-side filtering (hides legacy rows the write filter predates) ──────

test('isNoiseEditPath hides the same classes at query time', () => {
  // The watcher list only blocks NEW junk. Rows recorded before it was
  // tightened stay in the append-only log, so the analytics view filters too.
  for (const p of [
    'C:\\GIT\\vaultflow\\.metrics\\codex-events.pos.json',
    'C:\\GIT\\StockTool\\data\\market.duckdb',
    'C:\\GIT\\BUZZ\\data\\.gitkeep',
    'C:\\GIT\\proj\\node_modules\\pkg\\index.js',
  ]) {
    assert.equal(isNoiseEditPath(p), true, `${p} should be filtered from analytics`);
  }
});

test('isNoiseEditPath keeps real source and tolerates empty input', () => {
  assert.equal(isNoiseEditPath('C:\\Git\\vaultflow\\.claude\\helpers\\db.cjs'), false);
  assert.equal(isNoiseEditPath('C:\\GIT\\proj\\src\\App.tsx'), false);
  assert.equal(isNoiseEditPath(''), false);
  assert.equal(isNoiseEditPath(null), false);
});

test('write-time and read-time filters are the same function, not two copies', () => {
  // They were duplicated once and the copies disagreed: the watcher learned
  // about gitignored build output while the query path did not, so a Quartz
  // public/ tree kept the top 15 hot-file slots.
  assert.equal(db.isNoiseEditPath, isNoiseEditPath, 'db.cjs must re-export the shared predicate');
  const generated = 'C:\\GIT\\proj\\.metrics\\x.json';
  assert.equal(shouldIgnore(generated), isNoiseEditPath(generated));
});

// ── path casing (Windows reports the same file two ways) ──────────────────

test('mergePathCasing folds case-variant spellings and sums their counts', () => {
  // Claude Code's hook reports the session cwd's casing, the watcher reports
  // the watch root's. 214 files were split across two spellings covering 3,300
  // events, halving their apparent churn and listing each file twice.
  const merged = mergePathCasing([
    { file_path: 'C:\\GIT\\p\\a.ts', project: 'p', edit_count: 250 },
    { file_path: 'C:\\Git\\p\\a.ts', project: 'p', edit_count: 8 },
    { file_path: 'C:\\GIT\\p\\b.ts', project: 'p', edit_count: 5 },
  ]);
  assert.equal(merged.length, 2, 'the two spellings of a.ts must collapse to one row');
  assert.equal(merged[0].edit_count, 258, 'counts must be summed, not dropped');
  assert.equal(merged[0].file_path, 'C:\\GIT\\p\\a.ts', 'keeps the spelling most reporters used');
});

test('mergePathCasing keeps genuinely different files apart', () => {
  const merged = mergePathCasing([
    { file_path: 'C:\\GIT\\p\\a.ts', project: 'p', edit_count: 3 },
    { file_path: 'C:\\GIT\\p\\a.ts', project: 'other', edit_count: 4 },
    { file_path: 'C:\\GIT\\p\\B.ts', project: 'p', edit_count: 2 },
  ]);
  assert.equal(merged.length, 3, 'same path under a different project is a different row');
});

test('canonicalizePath returns real on-disk casing and survives missing files', () => {
  const real = canonicalizePath(path.join(helpers, 'db.cjs').toUpperCase());
  assert.match(real, /db\.cjs$/, 'must resolve to the actual filename casing');
  const gone = 'C:\\definitely\\not\\here\\x.ts';
  assert.equal(canonicalizePath(gone), gone, 'a deleted path passes through unchanged');
  assert.equal(canonicalizePath(''), '');
});
