/**
 * gen-context.mjs — static context injection for AI tools without hook systems
 *
 * Generates context files for Copilot, Codex (AGENTS.md), Cursor, and Windsurf
 * by reading from the vaultflow DB (stacks, memory, dictionary, recent patterns)
 * and writing thin, always-fresh pointer files.
 *
 * Every generated file includes a Shared Infrastructure section so all AI tools
 * (Claude Code, Copilot, Cursor, Codex) see the same vault tools, skills, and
 * vaultflow capabilities — not just project-specific context.
 *
 * Run after any significant session to keep AI context files current.
 *
 * Usage:
 *   node gen-context.mjs [project-path]   Generate for a project
 *   node gen-context.mjs --all            Generate for all watched projects
 */

import { createRequire } from 'node:module';
import path              from 'node:path';
import fs                from 'node:fs';
import os                from 'node:os';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);

// ── config ────────────────────────────────────────────────────────────────

/**
 * Write `newContent` to `filePath` only if the meaningful content differs
 * from what's already there. The trailing `*Generated by vaultflow gen-context — <iso>*`
 * line is stripped before comparison so a fresh timestamp alone does not
 * cause a rewrite (which would otherwise make every commit dirty and trigger
 * an endless post-commit regeneration loop in git).
 */
function writeIfChanged(filePath, newContent) {
  const stripStamp = (s) =>
    s.replace(/\*Generated by vaultflow gen-context — .*?\*\s*$/m, '').trimEnd();

  let existing = '';
  try { existing = fs.readFileSync(filePath, 'utf8'); } catch (_) {}

  if (stripStamp(existing) === stripStamp(newContent)) {
    return false;  // skipped — meaningful content unchanged
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, newContent, 'utf8');
  return true;
}

function loadConfig() {
  try {
    const yaml       = require('js-yaml');
    const configPath = require('../../config/resolve.cjs');
    if (fs.existsSync(configPath)) {
      return yaml.load(fs.readFileSync(configPath, 'utf8')) || {};
    }
  } catch (_) {}
  return {};
}

function getDb() {
  const db  = require('./db.cjs');
  const cfg = loadConfig();
  db.initialize(
    (cfg.paths  && cfg.paths.metrics_root)  || null,
    (cfg.storage && cfg.storage.db_file)    || null
  );
  return db;
}

// ── shared infrastructure loader ──────────────────────────────────────────

/**
 * Read the shared vault tools, skills, and vaultflow paths from config.
 * Returns everything needed to populate the Shared Infrastructure section.
 */
function loadSharedInfrastructure(cfg) {
  const paths = cfg.paths || {};

  // Skills: scan user_skills_dir for subdirectory names
  const skillsDir  = paths.user_skills_dir
    ? paths.user_skills_dir.replace(/\//g, path.sep)
    : path.join(os.homedir(), '.claude', 'skills');
  let skills = [];
  try {
    skills = fs.readdirSync(skillsDir, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name)
      .sort();
  } catch (_) {}

  // Vault tools index path
  const vaultToolsIndex = paths.vault_tools_index
    ? paths.vault_tools_index.replace(/\//g, path.sep)
    : path.join(os.homedir(), 'vault', 'tools', 'index.md');

  // Vault root
  const vaultRoot = paths.vault_root
    ? paths.vault_root.replace(/\//g, path.sep)
    : path.join(os.homedir(), 'vault');

  // Skills index (for Claude Code /skill-name invocation guide)
  const skillsIndex = paths.skills_index
    ? paths.skills_index.replace(/\//g, path.sep)
    : path.join(skillsDir, 'index.md');

  // vaultflow helpers dir (for DB search CLI)
  const helpersDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
  const vaultflowDir = path.resolve(helpersDir, '..', '..');

  return {
    skillsDir,
    skillsIndex,
    skills,
    vaultToolsIndex,
    vaultRoot,
    helpersDir,
    vaultflowDir,
    hasVaultTools: fs.existsSync(vaultToolsIndex),
    hasSkillsDir:  skills.length > 0,
  };
}

/**
 * Build the Shared Infrastructure markdown section.
 * Included in every generated file so all AI tools see the same shared resources.
 */
function buildSharedSection(infra) {
  const lines = ['## Shared Infrastructure'];
  lines.push('');
  lines.push('> These resources are cross-project. Check them before building anything new.');
  lines.push('');

  // Vault tools
  if (infra.hasVaultTools) {
    lines.push(`**Vault tools:** \`${infra.vaultToolsIndex}\``);
    lines.push('  30+ reusable scripts and utilities — check before implementing. Rule: exact match → use it; similar → adapt it; nothing close → build new and register.');
    lines.push('');
  }

  // Skills
  if (infra.hasSkillsDir) {
    const skillList = infra.skills.join(' · ');
    lines.push(`**Skills** (Claude Code: \`/skill-name\`, Codex: \`.agents/skills/\`):`);
    lines.push(`  ${skillList}`);
    if (fs.existsSync(infra.skillsIndex)) {
      lines.push(`  Full index: \`${infra.skillsIndex}\``);
    }
    lines.push('');
  }

  // vaultflow
  lines.push(`**vaultflow** (hook system + shared DB):`);
  lines.push(`  DB search:  \`node ${path.join(infra.helpersDir, 'db.cjs')} --search "query"\``);
  lines.push(`  Gen context: \`node ${path.join(infra.helpersDir, 'gen-context.mjs')}\``);
  lines.push(`  Model status: \`node ${path.join(infra.helpersDir, 'model-router.cjs')} --status\``);
  lines.push('');

  // Vault knowledge base
  lines.push(`**Vault:** \`${infra.vaultRoot}\``);
  lines.push(`  \`vault/tools/\` — reusable tools  |  \`vault/methodology/\` — engineering patterns`);
  lines.push(`  \`vault/domain/\` — domain knowledge  |  \`vault/agents/\` — agent registry`);

  return lines.join('\n');
}

// ── context builders ──────────────────────────────────────────────────────

/**
 * Build a stack summary string like "node · react · typescript · tailwind"
 */
function formatStacks(stacks) {
  return stacks.map(s => s.stack_key).join(' · ') || 'unknown';
}

/**
 * Build a compact bulleted block describing recent vaultflow activity for the
 * project. This is the same metadata Claude's SessionStart hook injects via
 * additionalContext — but here it gets baked into the static context files
 * (AGENTS.md, copilot-instructions.md) so Copilot, Codex, and any other tool
 * that reads those files at start gets the same prior-session awareness.
 *
 * Returns null when there's nothing useful to inject (new project / no
 * non-empty summaries) so callers can skip the section entirely.
 */
function buildRecentActivityBlock(db, projectName) {
  if (!projectName || !db || typeof db.getRecentSessionSummaries !== 'function') return null;
  let summaries = [];
  try { summaries = db.getRecentSessionSummaries(projectName, 3) || []; } catch (_) {}
  if (!summaries.length) return null;

  const lines = ['## Recent vaultflow Activity', ''];
  for (const s of summaries) {
    const when  = (s.summary_at || '').slice(0, 10);
    const dur   = s.duration_ms ? `${Math.round(s.duration_ms / 60000)}m` : '?';
    const files = (s.top_files || []).slice(0, 5).join(', ');
    const pats  = (s.patterns  || []).slice(0, 3).join(', ');
    lines.push(`- **${when}** (${dur}) — files: ${files || '—'}${pats ? `; patterns: ${pats}` : ''}`);
  }
  return lines.join('\n');
}

/**
 * Generate .github/copilot-instructions.md for a project.
 * Copilot reads this file automatically as project context.
 */
function genCopilotInstructions(projectPath, projectName, stacks, memoryEntries, infra, recentBlock) {
  const stackLine = formatStacks(stacks);
  const wikiPath  = path.join(projectPath, 'wiki', 'index.md');
  const hasWiki   = fs.existsSync(wikiPath);
  const llmsPath  = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms   = fs.existsSync(llmsPath);

  const memSection = memoryEntries.length > 0
    ? memoryEntries.slice(0, 5).map(e => `- **${e.title}**: ${e.body.slice(0, 120)}`).join('\n')
    : '- No recent memory entries.';

  const sharedSection = buildSharedSection(infra);

  const parts = [
    `# ${projectName} — Copilot Instructions`,
    '',
    `**Tech stack:** ${stackLine}`,
    '',
  ];

  if (hasLlms)  parts.push(`**Start here:** [\`wiki/llms.txt\`](wiki/llms.txt) — universal AI entry point`);
  if (hasWiki)  parts.push(`**Wiki:** [\`wiki/index.md\`](wiki/index.md) — project knowledge base`);
  if (hasLlms || hasWiki) parts.push('');

  if (recentBlock) {
    parts.push(recentBlock, '');
  }

  parts.push(
    '## Recent Context (from vaultflow)',
    '',
    memSection,
    '',
    sharedSection,
    '',
    '## Rules',
    '- Read wiki/llms.txt before answering domain questions.',
    '- Check vault tools index before building any utility or script.',
    '- Match existing code patterns — do not introduce new conventions.',
    '- Never commit secrets, connection strings, or .env files.',
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  );

  const content = parts.join('\n');
  const outPath = path.join(projectPath, '.github', 'copilot-instructions.md');
  writeIfChanged(outPath, content);
  return outPath;
}

/**
 * Generate AGENTS.md for a project (Codex CLI entry point).
 */
function genAgentsMd(projectPath, projectName, stacks, agents, infra, recentBlock) {
  const stackLine = formatStacks(stacks);
  const wikiPath  = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms   = fs.existsSync(wikiPath);

  const agentSection = agents.length > 0
    ? agents.slice(0, 10).map(a =>
        `| ${a.name} | ${a.source} | ${(a.description || '').slice(0, 80)} |`
      ).join('\n')
    : '| (no agents registered) | | |';

  const sharedSection = buildSharedSection(infra);

  // Skills table for Codex — path is user_skills_dir relative
  const skillRows = infra.skills.length > 0
    ? infra.skills.map(s => `| ${s} | \`${path.join(infra.skillsDir, s)}\` | \`/${s}\` in Claude Code |`).join('\n')
    : '| (no skills found) | | |';

  const content = [
    `# ${projectName} — Agent Roster`,
    '',
    `**Stack:** ${stackLine}`,
    hasLlms ? `**Context:** [wiki/llms.txt](wiki/llms.txt)` : '',
    '',
    ...(recentBlock ? [recentBlock, ''] : []),
    '## Available Agents',
    '',
    '| Agent | Source | Description |',
    '|-------|--------|-------------|',
    agentSection,
    '',
    '## Skills (invoke with /skill-name in Claude Code)',
    '',
    '| Skill | Path | Invocation |',
    '|-------|------|------------|',
    skillRows,
    '',
    sharedSection,
    '',
    '## Entry Points',
    hasLlms
      ? '1. Read `wiki/llms.txt` first — universal AI entry point'
      : '1. Read `CLAUDE.md` for project context',
    '2. Check `wiki/index.md` for domain knowledge',
    '3. Check `wiki/log.md` for recent session history',
    `4. Check \`${infra.vaultToolsIndex}\` before building any utility`,
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  ].join('\n');

  const outPath = path.join(projectPath, 'AGENTS.md');
  writeIfChanged(outPath, content);
  return outPath;
}

/**
 * Generate .cursor/rules/wiki.mdc for a project (Cursor MDC rule).
 */
function genCursorRule(projectPath, projectName, infra) {
  const wikiPath = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms  = fs.existsSync(wikiPath);
  const idxPath  = path.join(projectPath, 'wiki', 'index.md');
  const hasIdx   = fs.existsSync(idxPath);

  const skillList = infra.skills.slice(0, 10).join(', ');

  const content = [
    '---',
    'description: Wiki-first context for Cursor',
    'globs: ["**/*"]',
    'alwaysApply: true',
    '---',
    '',
    `# ${projectName} — Context`,
    '',
    ...(hasLlms ? ['Always read `wiki/llms.txt` before answering questions about this project.'] : []),
    ...(hasIdx  ? ['Project knowledge is in `wiki/index.md`.'] : []),
    '',
    'Match existing code patterns. Never introduce new conventions without reading the wiki first.',
    '',
    '## Shared Resources',
    '',
    ...(infra.hasVaultTools ? [`- **Vault tools:** \`${infra.vaultToolsIndex}\` — check before building any utility`] : []),
    ...(infra.hasSkillsDir  ? [`- **Skills:** ${skillList}`] : []),
    `- **vaultflow DB search:** \`node ${path.join(infra.helpersDir, 'db.cjs')} --search "query"\``,
    `- **Vault:** \`${infra.vaultRoot}\` — tools, methodology, domain knowledge`,
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  ].join('\n');

  const outPath = path.join(projectPath, '.cursor', 'rules', 'wiki.mdc');
  writeIfChanged(outPath, content);
  return outPath;
}

/**
 * Generate .vscode/mcp.json for a project (VS Code MCP registration — still used by VS Code itself).
 * Copilot CLI no longer reads .vscode/mcp.json; use .mcp.json at project root for that.
 */
function genVscodeMcp(projectPath, infra) {
  const mcpServerPath = path.join(infra.helpersDir, 'mcp-server.cjs').replace(/\\/g, '/');
  const content = JSON.stringify({
    servers: {
      vaultflow: {
        type: 'stdio',
        command: 'node',
        args: [mcpServerPath],
      },
    },
  }, null, 2) + '\n';

  const outPath = path.join(projectPath, '.vscode', 'mcp.json');
  writeIfChanged(outPath, content);
  return outPath;
}

/**
 * Generate .mcp.json at project root (Copilot CLI + Claude Code project-level MCP registration).
 * Copilot CLI migrated away from .vscode/mcp.json to this format.
 */
function genRootMcp(projectPath, infra) {
  const mcpServerPath = path.join(infra.helpersDir, 'mcp-server.cjs').replace(/\\/g, '/');
  const content = JSON.stringify({
    mcpServers: {
      vaultflow: {
        command: 'node',
        args: [mcpServerPath],
      },
    },
  }, null, 2) + '\n';

  const outPath = path.join(projectPath, '.mcp.json');
  writeIfChanged(outPath, content);
  return outPath;
}

// ── public API ────────────────────────────────────────────────────────────

/**
 * Generate all context files for a single project.
 *
 * @param {string} projectPath  Absolute path to the project root.
 * @returns {{ generated: string[] }}  Paths of files written.
 */
export async function generateForProject(projectPath) {
  const projectName = path.basename(projectPath);
  const cfg         = loadConfig();
  const db          = getDb();
  const infra       = loadSharedInfrastructure(cfg);
  const generated   = [];

  let stacks        = [];
  let memoryEntries = [];
  let agents        = [];

  try { stacks = db.getProjectStacks(projectName); } catch (_) {}

  // Pull relevant memory entries for this project
  try {
    memoryEntries = db.searchMemory(projectName, 5);
  } catch (_) {}

  // Get registered agents (Claude + Codex, sorted by use_count)
  try {
    const rawDb = db.raw();
    if (rawDb) {
      agents = rawDb.prepare(
        'SELECT name, source, description FROM vault_agents ORDER BY use_count DESC LIMIT 15'
      ).all();
    }
  } catch (err) {
    process.stderr.write(`[gen-context] agent registry unavailable: ${err.message}\n`);
  }

  // Recent activity block — shared across Copilot/Codex outputs so all three
  // tools (Claude, Copilot, Codex) see the same prior-session awareness from
  // a single source of truth.
  const recentBlock = buildRecentActivityBlock(db, projectName);

  // Copilot instructions
  try {
    const p = genCopilotInstructions(projectPath, projectName, stacks, memoryEntries, infra, recentBlock);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] copilot error: ${err.message}\n`);
  }

  // AGENTS.md
  try {
    const p = genAgentsMd(projectPath, projectName, stacks, agents, infra, recentBlock);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] agents.md error: ${err.message}\n`);
  }

  // Cursor rule
  try {
    const p = genCursorRule(projectPath, projectName, infra);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] cursor error: ${err.message}\n`);
  }

  // VS Code MCP registration (.vscode/mcp.json)
  try {
    const p = genVscodeMcp(projectPath, infra);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] vscode mcp error: ${err.message}\n`);
  }

  // Project-root MCP registration (.mcp.json — Copilot CLI + Claude Code)
  try {
    const p = genRootMcp(projectPath, infra);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] root mcp error: ${err.message}\n`);
  }

  return { generated };
}

// ── CLI ───────────────────────────────────────────────────────────────────

const thisPath = fileURLToPath(import.meta.url);

if (process.argv[1] === thisPath) {
  const args   = process.argv.slice(2);
  const target = args[0];

  (async () => {
    try {
      if (!target || target === '.') {
        const result = await generateForProject(process.cwd());
        result.generated.forEach(f => console.log(`  wrote: ${f}`));
      } else if (!target.startsWith('--')) {
        const absTarget = path.resolve(target);
        if (!fs.existsSync(absTarget)) {
          console.error(`Path not found: ${absTarget}`);
          process.exit(1);
        }
        const result = await generateForProject(absTarget);
        result.generated.forEach(f => console.log(`  wrote: ${f}`));
      } else if (target === '--all') {
        const cfg2       = loadConfig();
        const searchRoot = (cfg2.paths && cfg2.paths.watcher_watch_dir)
          ? cfg2.paths.watcher_watch_dir.replace(/\//g, path.sep)
          : path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
        let dirs = [];
        try {
          dirs = fs.readdirSync(searchRoot, { withFileTypes: true })
            .filter(d => d.isDirectory())
            .map(d => path.join(searchRoot, d.name))
            .filter(d => fs.existsSync(path.join(d, 'CLAUDE.md')) || fs.existsSync(path.join(d, 'package.json')));
        } catch (_) {}
        if (!dirs.length) {
          console.log(`No projects found under ${searchRoot}`);
        } else {
          for (const dir of dirs) {
            const result = await generateForProject(dir);
            result.generated.forEach(f => console.log(`  wrote: ${f}`));
          }
        }
      } else {
        console.error(`Unknown argument: ${target}`);
        console.error('Usage: node gen-context.mjs [project-path|--all]');
        process.exit(1);
      }
    } catch (err) {
      console.error('Error:', err.message);
      process.exit(1);
    }
  })();
}
