/**
 * gen-context.mjs — static context injection for AI tools without hook systems
 *
 * Generates context files for Copilot, Codex (AGENTS.md), Cursor, and Windsurf
 * by reading from the vaultflow DB (stacks, memory, dictionary, recent patterns)
 * and writing thin, always-fresh pointer files.
 *
 * Run after any significant session to keep AI context files current.
 *
 * Usage:
 *   node gen-context.mjs [project-path]   Generate for a project
 *   node gen-context.mjs --all            Generate for all watched projects
 */

import { createRequire } from 'node:module';
import path              from 'node:path';
import fs                from 'node:fs';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);

// ── config ────────────────────────────────────────────────────────────────

function loadConfig() {
  try {
    const yaml       = require('js-yaml');
    const configPath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      '../../config/vaultflow.yaml'
    );
    if (fs.existsSync(configPath)) {
      return yaml.load(fs.readFileSync(configPath, 'utf8'));
    }
  } catch (_) {}
  return {};
}

function getDb() {
  const db  = require('./db.cjs');
  const cfg = loadConfig();
  db.initialize(
    (cfg.paths  && cfg.paths.metrics_root)  || null,
    (cfg.storage && cfg.storage.db_file)    || null
  );
  return db;
}

// ── context builders ──────────────────────────────────────────────────────

/**
 * Build a stack summary string like "node · react · typescript · tailwind"
 */
function formatStacks(stacks) {
  return stacks.map(s => s.stack_key).join(' · ') || 'unknown';
}

/**
 * Generate .github/copilot-instructions.md for a project.
 * Copilot reads this file automatically as project context.
 */
function genCopilotInstructions(projectPath, projectName, stacks, memoryEntries) {
  const stackLine = formatStacks(stacks);
  const wikiPath  = path.join(projectPath, 'wiki', 'index.md');
  const hasWiki   = fs.existsSync(wikiPath);
  const llmsPath  = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms   = fs.existsSync(llmsPath);

  const memSection = memoryEntries.length > 0
    ? memoryEntries.slice(0, 5).map(e => `- **${e.title}**: ${e.body.slice(0, 120)}`).join('\n')
    : '- No recent memory entries.';

  const content = [
    `# ${projectName} — Copilot Instructions`,
    '',
    `**Tech stack:** ${stackLine}`,
    '',
    hasLlms  ? `**Start here:** [\`wiki/llms.txt\`](wiki/llms.txt) — universal AI entry point` : '',
    hasWiki  ? `**Wiki:** [\`wiki/index.md\`](wiki/index.md) — project knowledge base` : '',
    '',
    '## Recent Context (from vaultflow)',
    '',
    memSection,
    '',
    '## Rules',
    '- Read wiki/llms.txt before answering domain questions.',
    '- Match existing code patterns — do not introduce new conventions.',
    '- Never commit secrets, connection strings, or .env files.',
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  ].filter(l => l !== undefined).join('\n');

  const outDir = path.join(projectPath, '.github');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'copilot-instructions.md');
  fs.writeFileSync(outPath, content, 'utf8');
  return outPath;
}

/**
 * Generate AGENTS.md for a project (Codex CLI entry point).
 */
function genAgentsMd(projectPath, projectName, stacks, agents) {
  const stackLine = formatStacks(stacks);
  const wikiPath  = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms   = fs.existsSync(wikiPath);

  const agentSection = agents.length > 0
    ? agents.slice(0, 10).map(a =>
        `| ${a.name} | ${a.source} | ${(a.description || '').slice(0, 80)} |`
      ).join('\n')
    : '| (no agents registered) | | |';

  const content = [
    `# ${projectName} — Agent Roster`,
    '',
    `**Stack:** ${stackLine}`,
    hasLlms ? `**Context:** [wiki/llms.txt](wiki/llms.txt)` : '',
    '',
    '## Available Agents',
    '',
    '| Agent | Source | Description |',
    '|-------|--------|-------------|',
    agentSection,
    '',
    '## Entry Points',
    hasLlms
      ? '1. Read `wiki/llms.txt` first — universal AI entry point'
      : '1. Read `CLAUDE.md` for project context',
    '2. Check `wiki/index.md` for domain knowledge',
    '3. Check `wiki/log.md` for recent session history',
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  ].filter(l => l !== undefined).join('\n');

  const outPath = path.join(projectPath, 'AGENTS.md');
  fs.writeFileSync(outPath, content, 'utf8');
  return outPath;
}

/**
 * Generate .cursor/rules/wiki.mdc for a project (Cursor MDC rule).
 */
function genCursorRule(projectPath, projectName) {
  const wikiPath = path.join(projectPath, 'wiki', 'llms.txt');
  const hasLlms  = fs.existsSync(wikiPath);
  const idxPath  = path.join(projectPath, 'wiki', 'index.md');
  const hasIdx   = fs.existsSync(idxPath);

  const content = [
    '---',
    'description: Wiki-first context for Cursor',
    'globs: ["**/*"]',
    'alwaysApply: true',
    '---',
    '',
    `# ${projectName} — Context`,
    '',
    hasLlms ? 'Always read `wiki/llms.txt` before answering questions about this project.' : '',
    hasIdx  ? 'Project knowledge is in `wiki/index.md`.' : '',
    '',
    'Match existing code patterns. Never introduce new conventions without reading the wiki first.',
    '',
    `*Generated by vaultflow gen-context — ${new Date().toISOString()}*`,
  ].filter(l => l !== undefined).join('\n');

  const outDir = path.join(projectPath, '.cursor', 'rules');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'wiki.mdc');
  fs.writeFileSync(outPath, content, 'utf8');
  return outPath;
}

// ── public API ────────────────────────────────────────────────────────────

/**
 * Generate all context files for a single project.
 *
 * @param {string} projectPath  Absolute path to the project root.
 * @returns {{ generated: string[] }}  Paths of files written.
 */
export async function generateForProject(projectPath) {
  const projectName = path.basename(projectPath);
  const db          = getDb();
  const generated   = [];

  let stacks        = [];
  let memoryEntries = [];
  let agents        = [];

  try { stacks = db.getProjectStacks(projectName); } catch (_) {}

  // Pull relevant memory entries for this project
  try {
    memoryEntries = db.searchMemory(projectName, 5);
  } catch (_) {}

  // Get registered agents (Claude + Codex, sorted by use_count)
  try {
    const { DatabaseSync } = require('node:sqlite');
    const cfg      = loadConfig();
    const root     = cfg.paths && cfg.paths.metrics_root;
    const file     = (cfg.storage && cfg.storage.db_file) || 'vaultflow.db';
    if (root) {
      const rawDb = new DatabaseSync(path.join(root, file), { readOnly: true });
      agents = rawDb.prepare(
        'SELECT name, source, description FROM vault_agents ORDER BY use_count DESC LIMIT 15'
      ).all();
      rawDb.close();
    }
  } catch (err) {
    process.stderr.write(`[gen-context] agent registry unavailable: ${err.message}\n`);
  }

  // Copilot instructions
  try {
    const p = genCopilotInstructions(projectPath, projectName, stacks, memoryEntries);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] copilot error: ${err.message}\n`);
  }

  // AGENTS.md
  try {
    const p = genAgentsMd(projectPath, projectName, stacks, agents);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] agents.md error: ${err.message}\n`);
  }

  // Cursor rule
  try {
    const p = genCursorRule(projectPath, projectName);
    generated.push(p);
  } catch (err) {
    process.stderr.write(`[gen-context] cursor error: ${err.message}\n`);
  }

  return { generated };
}

// ── CLI ───────────────────────────────────────────────────────────────────

const thisPath = fileURLToPath(import.meta.url);

if (process.argv[1] === thisPath) {
  const args   = process.argv.slice(2);
  const target = args[0];

  (async () => {
    try {
      if (!target || target === '.') {
        const result = await generateForProject(process.cwd());
        result.generated.forEach(f => console.log(`  wrote: ${f}`));
      } else if (!target.startsWith('--')) {
        const absTarget = path.resolve(target);
        if (!fs.existsSync(absTarget)) {
          console.error(`Path not found: ${absTarget}`);
          process.exit(1);
        }
        const result = await generateForProject(absTarget);
        result.generated.forEach(f => console.log(`  wrote: ${f}`));
      } else {
        console.log('Usage: node gen-context.mjs [project-path]');
      }
    } catch (err) {
      console.error('Error:', err.message);
      process.exit(1);
    }
  })();
}
