# backup-to-archive.ps1 -- weekly additive backup of the active working drive
# into the long-term archive drive.
#
# WHY: the working set (C:\GIT) is where code is written; the archive (D:\GIT)
# is the copy kept so tools and knowledge survive a machine change. Those are
# different populations, not two views of one tree: at time of writing C:\GIT
# held 7 projects and D:\GIT held 35, of which 32 exist ONLY on the archive.
#
# SAFETY -- the three rules this script exists to enforce:
#
#   1. NEVER MIRROR. robocopy /MIR (or /PURGE) deletes destination files that
#      are absent from the source. Run that way, one pass would have destroyed
#      all 32 archive-only projects. This script never passes /MIR or /PURGE,
#      and the switches are asserted below so a future edit cannot slip one in.
#   2. NEVER REGRESS A FILE. /XO excludes source files OLDER than the copy
#      already in the archive, so an out-of-date working copy can never
#      overwrite newer archived content. BusinessCentral is the live example:
#      781 MB on C: against 3,860 MB on D:.
#   3. NEVER BACK UP GENERATED BYTES. node_modules/bin/obj/.metrics and friends
#      are excluded -- they are large, regenerable, and machine-specific. .git
#      IS included: history is the most valuable thing to preserve.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/backup-to-archive.ps1
#   powershell -ExecutionPolicy Bypass -File scripts/backup-to-archive.ps1 -DryRun
#   powershell -ExecutionPolicy Bypass -File scripts/backup-to-archive.ps1 -Source C:\GIT -Archive D:\GIT
#
# NOTE: keep this file ASCII-only. It has no BOM, so Windows PowerShell 5.1
# reads it as ANSI and UTF-8 punctuation becomes parse-breaking smart quotes.

param(
    [string]$Source  = 'C:\GIT',
    [string]$Archive = 'D:\GIT',
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Step($m) { Write-Host "==> $m" }
function Ok($m)   { Write-Host "    $m" -ForegroundColor Green }
function Warn($m) { Write-Host "    $m" -ForegroundColor Yellow }

if (-not (Test-Path $Source))  { throw "Source not found: $Source" }
if (-not (Test-Path $Archive)) { throw "Archive not found: $Archive. Is the drive connected?" }

# Generated / machine-specific trees. Excluded by NAME at any depth (/XD).
$ExcludeDirs = @(
    'node_modules', '.metrics', 'bin', 'obj', 'dist', 'build',
    '.venv', 'venv', '__pycache__', '.next', '.turbo', 'coverage', '.pytest_cache'
)
# Runtime data that is large and reproducible. Excluded by NAME pattern (/XF).
$ExcludeFiles = @('*.db', '*.db-wal', '*.db-shm', '*.duckdb', '*.parquet', '*.log', 'watcher.pid')

# Additive-only switch set. /E recurse incl. empty dirs, /XO never regress,
# /R:1 /W:1 fail fast on locked files, /NFL /NDL quiet per-file noise.
$Switches = @('/E', '/XO', '/R:1', '/W:1', '/NFL', '/NDL', '/NP')
if ($DryRun) { $Switches += '/L' }   # /L = list only, copy nothing

# Rule 1, enforced rather than merely documented.
foreach ($bad in @('/MIR', '/PURGE')) {
    if ($Switches -contains $bad) { throw "REFUSING TO RUN: $bad would delete archive-only projects." }
}

Step "Backup $Source -> $Archive$(if ($DryRun) { '  [DRY RUN - nothing will be written]' })"

$projects = Get-ChildItem -Path $Source -Directory -ErrorAction SilentlyContinue
if (-not $projects) { Warn "No project directories under $Source"; exit 0 }

$results = @()
foreach ($p in $projects) {
    $dest = Join-Path $Archive $p.Name
    $isNew = -not (Test-Path $dest)

    $args = @($p.FullName, $dest) + $Switches +
            @('/XD') + $ExcludeDirs +
            @('/XF') + $ExcludeFiles

    $out = & robocopy @args 2>&1
    $code = $LASTEXITCODE

    # robocopy exit codes are a bitmask: 0-7 are success (0 = nothing to do,
    # 1 = files copied, 2 = extra files present, 4 = mismatched). 8+ is failure.
    # Treating any nonzero as an error is the classic robocopy scripting bug.
    $status = if ($code -ge 8) { 'FAIL' } elseif ($code -eq 0) { 'up-to-date' } else { 'copied' }

    $copied = ($out | Select-String -Pattern '^\s*Files\s*:' | Select-Object -First 1)
    $results += [pscustomobject]@{
        Project = $p.Name
        Status  = $status
        New     = $isNew
        Code    = $code
    }
    $label = "$($p.Name)$(if ($isNew) { ' (new to archive)' } else { '' })"
    if ($status -eq 'FAIL') { Warn "$label -- robocopy exit $code" } else { Ok "$label -- $status" }
}

$failed = @($results | Where-Object { $_.Status -eq 'FAIL' })

# Heartbeat, so `vaultflow doctor` can report whether the backup is actually
# running. The nightly task silently stopped firing for 99h once; a backup that
# fails quietly is worse than no backup, because it is trusted.
$stamp = @{
    last_run_at = (Get-Date).ToUniversalTime().ToString('o')
    source      = $Source
    archive     = $Archive
    dry_run     = [bool]$DryRun
    projects    = $results.Count
    failed      = $failed.Count
    detail      = $results
} | ConvertTo-Json -Depth 4

$metricsDir = Join-Path (Split-Path -Parent $PSScriptRoot) '.metrics'
if (Test-Path $metricsDir) {
    $hb = Join-Path $metricsDir 'archive-backup-heartbeat.json'
    if (-not $DryRun) {
        # WriteAllText, not Set-Content -Encoding utf8: in Windows PowerShell 5.1
        # that switch emits UTF-8 WITH a BOM, and Node's JSON.parse rejects the
        # leading U+FEFF outright ("Unexpected token"). The doctor check that
        # reads this file would have failed on every single run.
        [System.IO.File]::WriteAllText($hb, $stamp, (New-Object System.Text.UTF8Encoding($false)))
    }
    Write-Host ""
    Write-Host "Heartbeat: $hb"
}

Write-Host ""
Write-Host "$($results.Count) project(s) processed, $($failed.Count) failed."
if ($failed.Count -gt 0) { exit 1 }
exit 0
